name: publish

on:
  push:
    branches: [ main ]

jobs:
  publish-tauri:
    permissions: { contents: write }
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
          - platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - uses: dtolnay/rust-toolchain@stable
      - name: build deps (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - run: npm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'FinanceTracker v__VERSION__'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
      - name: Copy release to public repo
        uses: softprops/action-gh-release@v1
        with:
          repository: MauroVitoOFF/financetracker-releases
          token: ${{ secrets.GITHUB_TOKEN }}
